// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RanchoMqttApi;

#nullable disable

namespace RanchoMqttApi.Migrations._02SeedDatosIniciales
{
    [DbContext(typeof(DBContext))]
    [Migration("20260731163315_SeedDatosIniciales")]
    partial class SeedDatosIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RanchoMqttApi.HistorialEstadoRelei", b =>
                {
                    b.Property<int>("idHistorialEstadoRelei")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorialEstadoRelei"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("exito")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idRele")
                        .HasColumnType("integer");

                    b.HasKey("idHistorialEstadoRelei");

                    b.HasIndex("idRele");

                    b.ToTable("HistorialEstadoReleis");
                });

            modelBuilder.Entity("RanchoMqttApi.LecturaTemperatura", b =>
                {
                    b.Property<int>("idLecturaTemperatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idLecturaTemperatura"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idSensor")
                        .HasColumnType("integer");

                    b.Property<double>("temperatura")
                        .HasColumnType("double precision");

                    b.HasKey("idLecturaTemperatura");

                    b.HasIndex("idSensor");

                    b.ToTable("LecturaTemperaturas");
                });

            modelBuilder.Entity("RanchoMqttApi.Rele", b =>
                {
                    b.Property<int>("idRele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRele"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idTipoRele")
                        .HasColumnType("integer");

                    b.Property<int>("idZona")
                        .HasColumnType("integer");

                    b.HasKey("idRele");

                    b.HasIndex("idTipoRele");

                    b.HasIndex("idZona");

                    b.ToTable("Rele");

                    b.HasData(
                        new
                        {
                            idRele = 1,
                            Nombre = "Riego zona 1",
                            idTipoRele = 1,
                            idZona = 1
                        });
                });

            modelBuilder.Entity("RanchoMqttApi.Sensor", b =>
                {
                    b.Property<int>("idSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idSensor"));

                    b.Property<int>("idTipoSensor")
                        .HasColumnType("integer");

                    b.Property<int>("idZona")
                        .HasColumnType("integer");

                    b.Property<string>("nombreSensor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idSensor");

                    b.HasIndex("idTipoSensor");

                    b.HasIndex("idZona");

                    b.ToTable("Sensor");

                    b.HasData(
                        new
                        {
                            idSensor = 1,
                            idTipoSensor = 1,
                            idZona = 1,
                            nombreSensor = "Sensor temperatura"
                        });
                });

            modelBuilder.Entity("RanchoMqttApi.TipoRele", b =>
                {
                    b.Property<int>("idTipoRele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoRele"));

                    b.Property<string>("nombreRele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTipoRele");

                    b.ToTable("TipoReles");

                    b.HasData(
                        new
                        {
                            idTipoRele = 1,
                            nombreRele = "riego"
                        },
                        new
                        {
                            idTipoRele = 2,
                            nombreRele = "focos"
                        });
                });

            modelBuilder.Entity("RanchoMqttApi.TipoSensor", b =>
                {
                    b.Property<int>("idTipoSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoSensor"));

                    b.Property<string>("nombreSensor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTipoSensor");

                    b.ToTable("TipoSensores");

                    b.HasData(
                        new
                        {
                            idTipoSensor = 1,
                            nombreSensor = "temperatura"
                        });
                });

            modelBuilder.Entity("RanchoMqttApi.Zona", b =>
                {
                    b.Property<int>("idZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idZona"));

                    b.Property<string>("zonaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idZona");

                    b.ToTable("Zona");

                    b.HasData(
                        new
                        {
                            idZona = 1,
                            zonaName = "Zona 1"
                        });
                });

            modelBuilder.Entity("RanchoMqttApi.HistorialEstadoRelei", b =>
                {
                    b.HasOne("RanchoMqttApi.Rele", "rele")
                        .WithMany()
                        .HasForeignKey("idRele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rele");
                });

            modelBuilder.Entity("RanchoMqttApi.LecturaTemperatura", b =>
                {
                    b.HasOne("RanchoMqttApi.Sensor", "sensor")
                        .WithMany()
                        .HasForeignKey("idSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sensor");
                });

            modelBuilder.Entity("RanchoMqttApi.Rele", b =>
                {
                    b.HasOne("RanchoMqttApi.TipoRele", "tipoRele")
                        .WithMany()
                        .HasForeignKey("idTipoRele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RanchoMqttApi.Zona", "zona")
                        .WithMany()
                        .HasForeignKey("idZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoRele");

                    b.Navigation("zona");
                });

            modelBuilder.Entity("RanchoMqttApi.Sensor", b =>
                {
                    b.HasOne("RanchoMqttApi.TipoSensor", "tipoSensor")
                        .WithMany()
                        .HasForeignKey("idTipoSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RanchoMqttApi.Zona", "zona")
                        .WithMany()
                        .HasForeignKey("idZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoSensor");

                    b.Navigation("zona");
                });
#pragma warning restore 612, 618
        }
    }
}
