// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RanchoMqttApi;

#nullable disable

namespace RanchoMqttApi.Migrations._00InitCreation
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RanchoMqttApi.HistorialEstadoRelei", b =>
                {
                    b.Property<int>("idHistorialEstadoRelei")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorialEstadoRelei"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("exito")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idRele")
                        .HasColumnType("integer");

                    b.HasKey("idHistorialEstadoRelei");

                    b.HasIndex("idRele");

                    b.ToTable("HistorialEstadoReleis");
                });

            modelBuilder.Entity("RanchoMqttApi.LecturaTemperatura", b =>
                {
                    b.Property<int>("idLecturaTemperatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idLecturaTemperatura"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idSensor")
                        .HasColumnType("integer");

                    b.Property<int>("sensoridSensor")
                        .HasColumnType("integer");

                    b.Property<double>("temperatura")
                        .HasColumnType("double precision");

                    b.HasKey("idLecturaTemperatura");

                    b.HasIndex("sensoridSensor");

                    b.ToTable("LecturaTemperaturas");
                });

            modelBuilder.Entity("RanchoMqttApi.Rele", b =>
                {
                    b.Property<int>("idRele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRele"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idZona")
                        .HasColumnType("integer");

                    b.HasKey("idRele");

                    b.HasIndex("idZona");

                    b.ToTable("Rele");
                });

            modelBuilder.Entity("RanchoMqttApi.Sensor", b =>
                {
                    b.Property<int>("idSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idSensor"));

                    b.Property<int>("idZona")
                        .HasColumnType("integer");

                    b.Property<string>("nombreSensor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idSensor");

                    b.HasIndex("idZona");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("RanchoMqttApi.Zona", b =>
                {
                    b.Property<int>("idZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idZona"));

                    b.Property<string>("zonaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idZona");

                    b.ToTable("Zona");
                });

            modelBuilder.Entity("RanchoMqttApi.HistorialEstadoRelei", b =>
                {
                    b.HasOne("RanchoMqttApi.Rele", "rele")
                        .WithMany()
                        .HasForeignKey("idRele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rele");
                });

            modelBuilder.Entity("RanchoMqttApi.LecturaTemperatura", b =>
                {
                    b.HasOne("RanchoMqttApi.Sensor", "sensor")
                        .WithMany()
                        .HasForeignKey("sensoridSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sensor");
                });

            modelBuilder.Entity("RanchoMqttApi.Rele", b =>
                {
                    b.HasOne("RanchoMqttApi.Zona", "zona")
                        .WithMany()
                        .HasForeignKey("idZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("zona");
                });

            modelBuilder.Entity("RanchoMqttApi.Sensor", b =>
                {
                    b.HasOne("RanchoMqttApi.Zona", "zona")
                        .WithMany()
                        .HasForeignKey("idZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("zona");
                });
#pragma warning restore 612, 618
        }
    }
}
